// Generated by scripts/make-sample-art.mjs. The pretend shop used to demonstrate feeds and page reading.
export type DemoProduct = { id: string; name: string; price: number; rrp: number | null; category: string; description: string };
export const DEMO_PRODUCTS: DemoProduct[] = [
  {
    "id": "h-1001",
    "name": "Harbour Canvas Trainers",
    "price": 54,
    "rrp": 69,
    "category": "Shoes",
    "description": "Canvas trainers with a cushioned insole and rubber toe cap."
  },
  {
    "id": "h-1002",
    "name": "Stone Chino Trousers",
    "price": 38,
    "rrp": null,
    "category": "Trousers",
    "description": "Slim-fit cotton chinos with a hint of stretch."
  },
  {
    "id": "h-1003",
    "name": "Pine Quilted Parka",
    "price": 129,
    "rrp": 159,
    "category": "Coats",
    "description": "Quilted parka with a fur-trim hood and fleece lining."
  },
  {
    "id": "h-1004",
    "name": "Tan Leather Tote Bag",
    "price": 75,
    "rrp": null,
    "category": "Bags",
    "description": "Soft leather tote with an internal zip pocket."
  },
  {
    "id": "h-1005",
    "name": "Sky Oxford Shirt",
    "price": 32,
    "rrp": null,
    "category": "Shirts",
    "description": "Easy-iron cotton Oxford shirt, regular fit."
  },
  {
    "id": "h-1006",
    "name": "Cherry Retro Sneakers",
    "price": 62,
    "rrp": 80,
    "category": "Shoes",
    "description": "Retro-style low-top sneakers in washed cherry red."
  },
  {
    "id": "h-1007",
    "name": "Midnight Crew Sweatshirt",
    "price": 29,
    "rrp": null,
    "category": "Sweatshirts",
    "description": "Brushed-back crew neck sweatshirt in midnight navy."
  },
  {
    "id": "h-1008",
    "name": "Sage Everyday Backpack",
    "price": 48,
    "rrp": null,
    "category": "Bags",
    "description": "Padded 20-litre backpack with a laptop sleeve."
  },
  {
    "id": "h-1009",
    "name": "Black Chelsea Boots",
    "price": 89,
    "rrp": null,
    "category": "Shoes",
    "description": "Leather Chelsea boots with elasticated sides."
  },
  {
    "id": "h-1010",
    "name": "Oat Cotton Polo",
    "price": 24,
    "rrp": null,
    "category": "Shirts",
    "description": "Piqué cotton polo shirt in oat."
  },
  {
    "id": "h-1011",
    "name": "Brick Heavy Hoodie",
    "price": 45,
    "rrp": null,
    "category": "Hoodies",
    "description": "Heavyweight fleece-backed hoodie in brick red."
  },
  {
    "id": "h-1012",
    "name": "Navy Weekender Bag",
    "price": 95,
    "rrp": null,
    "category": "Bags",
    "description": "Canvas weekender with leather trim and a shoulder strap."
  }
];
